# Generated by Django 4.0.1 on 2022-02-12 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('share_link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 13, 56, 9, 577640, tzinfo=utc)),
        ),
    ]
