# Generated by Django 4.0.1 on 2022-02-12 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('share_link', '0005_alter_sharelink_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 13, 58, 41, 997006, tzinfo=utc)),
        ),
    ]
