# Generated by Django 4.0.1 on 2022-02-12 14:00

from django.db import migrations, models
import share_link.models


class Migration(migrations.Migration):

    dependencies = [
        ('share_link', '0007_alter_sharelink_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='expiry_date',
            field=models.DateTimeField(default=share_link.models.now_plus_7),
        ),
    ]
