# Generated by Django 4.0.1 on 2022-02-12 19:00

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('share_link', '0009_alter_sharelink_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
    ]
