# Generated by Django 4.0.1 on 2022-02-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_link', '0011_alter_shareddocumentimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='sender',
        ),
    ]
