# Generated by Django 4.0.1 on 2022-02-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_link', '0013_sharelink_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='sender',
        ),
    ]
