# Generated by Django 4.0.1 on 2022-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_link', '0014_remove_sharelink_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='key',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
