# Generated by Django 4.0.1 on 2022-02-10 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_mobile_number_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+?977)?\\d{10}$')]),
        ),
    ]
